# Generated by Django 4.2.1 on 2023-06-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='LATITUDE'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='LONGITUDE'),
        ),
        migrations.AlterField(
            model_name='story',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='LATITUDE'),
        ),
        migrations.AlterField(
            model_name='story',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='LONGITUDE'),
        ),
    ]
