# Generated by Django 4.2.1 on 2023-05-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='address',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='city',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='country',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='zipcode',
        ),
        migrations.RemoveField(
            model_name='story',
            name='address',
        ),
        migrations.RemoveField(
            model_name='story',
            name='city',
        ),
        migrations.RemoveField(
            model_name='story',
            name='country',
        ),
        migrations.RemoveField(
            model_name='story',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, max_length=200, verbose_name='CONTENT'),
        ),
    ]
