# Generated by Django 4.2.1 on 2023-06-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='mapID',
            field=models.CharField(blank=True, max_length=30, verbose_name='MAPID'),
        ),
        migrations.AlterField(
            model_name='story',
            name='mapID',
            field=models.CharField(blank=True, max_length=30, verbose_name='MAPID'),
        ),
    ]
