# Generated by Django 4.2.1 on 2023-05-31 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0002_post_like_post_like_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='main_image',
        ),
    ]
