# Generated by Django 4.2.1 on 2023-06-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0002_alter_pin_latitude_alter_pin_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='LATITUDE'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='LONGITUDE'),
        ),
        migrations.AlterField(
            model_name='story',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='LATITUDE'),
        ),
        migrations.AlterField(
            model_name='story',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='LONGITUDE'),
        ),
    ]
