# Generated by Django 4.2.1 on 2023-08-13 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0002_alter_post_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='socialmedia.post'),
        ),
    ]
