# Generated by Django 4.2.1 on 2023-07-29 22:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialmedia', '0002_post_tagged_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tagged_users',
            field=models.ManyToManyField(blank=True, related_name='tagging_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
