# Generated by Django 4.2.1 on 2023-05-31 22:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialmedia', '0003_remove_post_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_users',
            field=models.ManyToManyField(null=True, related_name='like_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
