# Generated by Django 4.2.1 on 2023-06-03 00:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialmedia', '0003_alter_pin_latitude_alter_pin_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bookmark_users',
            field=models.ManyToManyField(blank=True, related_name='bookmark_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
