# Generated by Django 4.2.1 on 2023-06-04 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0004_remove_post_comment_count_remove_post_like_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='like_count',
        ),
    ]
