# Generated by Django 4.2.1 on 2023-08-29 18:23

import accounts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=20, verbose_name='NAME')),
                ('uname', models.CharField(blank=True, max_length=20, null=True, verbose_name='UNAME')),
                ('email', models.EmailField(max_length=40, unique=True, verbose_name='EMAIL')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='AGE')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='GENDER')),
                ('image', models.ImageField(blank=True, default=accounts.models.User.default_image_path, null=True, upload_to=accounts.models.User.upload_to_func, verbose_name='IMAGE')),
                ('introduction', models.TextField(blank=True, max_length=200, null=True, verbose_name='INTRODUCTION')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('following_set', models.ManyToManyField(blank=True, related_name='follower_set', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
