# Generated by Django 4.2.1 on 2023-07-31 16:10

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.User.upload_to_func, verbose_name='IMAGE'),
        ),
    ]
