# Generated by Django 4.2.1 on 2023-08-19 08:56

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default=accounts.models.User.default_image_path, null=True, upload_to=accounts.models.User.upload_to_func, verbose_name='IMAGE'),
        ),
    ]
