# Generated by Django 4.2.1 on 2023-08-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_follower_set_alter_user_following_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=40, verbose_name='EMAIL'),
        ),
    ]
