# Generated by Django 4.2.1 on 2023-08-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uname',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='UNAME'),
        ),
    ]
